### ISSUE TITLE
desktop页面上的微博和mobile上的微博不一样

### ISSUE THREAD

**Issue by hanfu** [czy1999/weibo-topic-spider#10]
以肺炎患者求助超话为例
m端的微博每小时只有几个
d端的微博每分钟都有几个

**Comment by czy1999** [comment]
实际上是一样的。因为PC端显示的是最后评论时间，而手机端显示发表微博时间，两者内容一致，只是看起来好像手机端微博频次少很多。

**Comment by hanfu** [comment]
是哦 谢谢指正!
