### ISSUE TITLE
相关问题

### ISSUE THREAD

**Issue by w4yne97** [czy1999/weibo-topic-spider#11]
您好，想请教一下，我想添加一个功能：若是转发别人的微博，爬取原微博博主的名称；最近才接触爬虫，才疏学浅，望赐教。

**Comment by czy1999** [comment]
建议学习一下XPATH和CSS Selector，结合Chrome的浏览器检查功能，可以快速定位并添加所要爬取的目标，在爬虫的代码里也有一些例子，欢迎继续交流:P
![git](https://user-images.githubusercontent.com/17674230/74650435-af999180-51bc-11ea-8d3b-b050cff22525.jpg)

![css](https://user-images.githubusercontent.com/17674230/74650643-1dde5400-51bd-11ea-9bc4-a0ddbd67be8b.jpg)
