### ISSUE TITLE
是超级话题 但是出现以下问题

### ISSUE THREAD

**Issue by xuexifight** [czy1999/weibo-topic-spider#13]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='app']/div[1]/div[1]/div[1]/div[4]/div/div/div/a/div[2]/h4[1]"}
  (Session info: chrome=80.0.3987.100)

**Comment by xuexifight** [comment]
请问一下这是哪里出错了呢，感谢

**Comment by czy1999** [comment]
这个错误是因为程序没有找到话题的阅读量，请问爬取的话题是什么？

**Comment by xuexifight** [comment]
-日本肺炎疫情，通过另一种方法解决了，用的selenium

**Comment by xuexifight** [comment]
但是这个是直接爬取的某微博用户的某条微博所有评论

**Comment by xuexifight** [comment]
日本肺炎疫情，好像就是定位不到。

**Comment by czy1999** [comment]
我看了一下，主要是因为“日本肺炎疫情”不是微博超级话题，所以程序自动爬取的时候很多超级话题的标签爬取不到，爬取的话需要对程序进行修改，可以参考一下我在这个issue里的附上的代码，将话题修改为 #日本疫情# 即可（注意添加#号）
[普通话题代码](https://github.com/czy1999/weibo-topic-spider/issues/3)

**Comment by xuexifight** [comment]
我懂了，我理解错了。感谢
