### ISSUE TITLE
能否在超话内输入关键词再爬取相应微博

### ISSUE THREAD

**Issue by jiangxue0210** [czy1999/weibo-topic-spider#14]
求指教，请问可以模拟手机端输入关键词后，爬取超话内带有相应关键词的微博吗？
或者可以只爬取某一段时间内的文本吗？感谢解答

**Comment by czy1999** [comment]
可以实现，想要爬取带超话内部有关键词keyword的微博，只需要在weibo-topic-spyder.py 70-71行之间加入以下代码：
```Python
if keyword not in weibo_content:
  continue
```
此处keyword为你设定的关键词
