### ISSUE TITLE
想请教excelSave的问题

### ISSUE THREAD

**Issue by sakura-iv** [czy1999/weibo-topic-spider#15]
我用的Python3.7版本，excelSave这个包貌似没法pip install，显示没有对应版本诶，而且网上也查不到这个包相关信息...想请教一下怎么解决呀？

**Comment by czy1999** [comment]
这个不是包，是导入excelSave.py里的函数，所以找不到😂
只要把excelSave.py和weibo-topic-spider.py放在同一个目录下即可

**Comment by sakura-iv** [comment]
原来是这样，因为我是用的notebook运行调试，看了您说的就用了sysappend就好啦，谢谢您！但是我在运行过程中又出现新的问题，暂时没有搞明白是怎么回事，实在很麻烦您！
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//img[@src ='http://simg.s.weibo.com/20181009184948_super_topic_bg_small.png']"}
  (Session info: chrome=77.0.3865.120)
报了这个错误，应该是这一行出错的 
elem = driver.find_element_by_xpath("//img[@src ='http://simg.s.weibo.com/20181009184948_super_topic_bg_small.png']")
我爬取的超话是#华为向武汉捐赠3000万#，请问您知道要怎么处理吗，非常感谢！

**Comment by czy1999** [comment]
因为#华为向武汉捐赠3000万#不是微博超级话题，所以程序自动爬取的时候很多超级话题的标签爬取不到，爬取的话需要对程序进行修改，可以参考一下我在这个issue里的附上的代码，将话题修改为#华为向武汉捐赠3000万# 即可（注意添加#号）
[普通话题代码](https://github.com/czy1999/weibo-topic-spider/issues/3)

**Comment by sakura-iv** [comment]
这个txt文件打开后很多标点符号都没有了...我再原样加上后还是报一样的错...请问或许可以发一个py文件做参考吗，实在是打扰您了...

**Comment by czy1999** [comment]
项目已经更新

**Comment by sakura-iv** [comment]
问题已解决，非常非常感谢您！
