### ISSUE TITLE
输出的问题

### ISSUE THREAD

**Issue by lic601** [czy1999/weibo-topic-spider#18]
重复写入第456条数据，数据重复， 一直在重复这一步，请问怎么回事呀。

**Comment by czy1999** [comment]
请问爬取的话题是什么？然后请观察一下浏览器微博的界面是否仍在拉取数据

**Comment by lic601** [comment]
话题是  江山娇与红旗漫 ，界面仍在拉取数据，但是我看了下拉出来是重复的。这种情况是不是爬完该话题下的所有微博了？

**Comment by czy1999** [comment]
爬虫爬取的数据都来自于浏览器，如果下拉出来是重复的。一般可以认为是爬取完毕；也可能是微博限制，可以换一个账号重新爬取试试
