### ISSUE TITLE
这个现在还可以用吗？

### ISSUE THREAD

**Issue by ghost** [czy1999/weibo-topic-spider#2]
为什么会报这样的错呀？

NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='loginName']"}
  (Session info: chrome=75.0.3770.100)

**Comment by koalagiraffe** [comment]
> 为什么会报这样的错呀？
> 
> NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='loginName']"}
> (Session info: chrome=75.0.3770.100)

我也报了这个错误，应该是直接打开m.weibo.com 是没有登录窗口的，使用Cookies，文件里注释掉的部分有一个语句是直接打开登录页面的，测试了那样可以使用。但是往下爬还有点坑- -

**Comment by czy1999** [comment]
这个错误是因为登陆网址注释错了，已经修复
然后因为m.weibo.com布局发生了较大的改变，后面的控件都需要重新拉取，此处待修复

**Comment by koalagiraffe** [comment]
> 这个错误是因为登陆网址注释错了，已经修复
> 然后因为m.weibo.com布局发生了较大的改变，后面的控件都需要重新拉取，此处待修复

期待你的更新

**Comment by czy1999** [comment]
已修复问题
