### ISSUE TITLE
微博网页限制只能显示50页内容

### ISSUE THREAD

**Issue by TonG8066** [czy1999/weibo-topic-spider#21]
网页版微博最多只显示50页内容，所以不管设置数量多大，最多也只能爬1000多条。听说手机版微博没有这个限制，不知道有没有办法解决呢？

**Comment by czy1999** [comment]
本项目爬取的就是手机网页版微博，没有页数限制，已经测试可以超过一千条

**Comment by TonG8066** [comment]
> 本项目爬取的就是手机网页版微博，没有页数限制，已经测试可以超过一千条

谢谢回复，我之前设置5000条结果只爬了1000多条，可能是因为数据重复的原因，误会了
