### ISSUE TITLE
无法显示全文

### ISSUE THREAD

**Issue by miaomiaorepo** [czy1999/weibo-topic-spider#8]
现在是没有进入到每一条博文的页面，所以如果这条博文正文比较长，就会被隐藏掉，博文显示的就是【...全文】，爬下来的时候也爬不到全文。例如sample“肺炎.xls”第七行。请问如何解决，如果还要同时下载图片呢？

**Comment by AslanFu** [comment]
同求

**Comment by czy1999** [comment]
应该是可以做到的，通过点击进入每一条微博可以获取全文和图片，此处待更新

**Comment by czy1999** [comment]
已更新，目前可爬取全文
